# exchange_markets.py

# exchange_markets.py

exchange_market_lists = {
    'Binance': {
        'MATIC': 'MATICUSDT',
        'QUICK': 'QUICKUSDT',
        'SUSHI': 'SUSHIUSDT',
        'WMATIC': 'WMATICUSDT',
        'AAVE': 'AAVEUSDT',
        'WBTC': 'BTCUSDT',
        'USDC': 'USDCUSDT',
        'DAI': 'DAIUSDT',
        'CRV': 'CRVUSDT',
        'WETH': 'ETHUSDT',
        'SNX': 'SNXUSDT',
        'LINK': 'LINKUSDT',
        'UNI': 'UNIUSDT',
        'RENBTC': 'RENBTCUSDT',
        'BADGER': 'BADGERUSDT',
        'RARI': 'RARIUSDT',
        'FRAX': 'FRAXUSDT',
        'CEL': 'CELUSDT',
        'REN': 'RENUSDT',
        'BZRX': 'BZRXUSDT',
        'USDT': 'USDTUSDT',
        'PICKLE': 'PICKLEUSDT',
        'SPELL': 'SPELLUSDT',
        'GHST': 'GHSTUSDT',
        'CURVE': 'CURVEUSDT',
        
        
        # Add or modify more assets and trading pairs for Binance
    },
    
#---------------------------------------------------------------------------------------------------------------
    'Kraken': {
        'MATIC': 'MATICUSD',
        'QUICK': 'QUICKUSD',
        'SUSHI': 'SUSHIUSD',
        'WMATIC': 'WMATICUSD',
        'AAVE': 'AAVEUSD',
        'WBTC': 'XBTUSD',
        'USDC': 'USDCUSD',
        'DAI': 'DAIUSD',
        'CRV': 'CRVUSD',
        'WETH': 'ETHUSD',
        'SNX': 'SNXUSD',
        'LINK': 'LINKUSD',
        'UNI': 'UNIUSD',
        'RENBTC': 'RENBTCUSD',
        'BADGER': 'BADGERUSD',
        'RARI': 'RARIUSD',
        'FRAX': 'FRAXUSD',
        'CEL': 'CELUSD',
        'REN': 'RENUSD',
        'BZRX': 'BZRXUSD',
        'USDT': 'USDTUSD',
        'PICKLE': 'PICKLEUSD',
        'SPELL': 'SPELLUSD',
        'GHST': 'GHSTUSD',
        'CURVE': 'CRVUSD',
        # Add or modify more assets and trading pairs for Kraken
    },
    
    'coinbase': {
        'MATIC': 'MATIC-USD',
        'QUICK': 'QUICK-USD',
        'SUSHI': 'SUSHI-USD',
        'WMATIC': 'WMATIC-USD',
        'AAVE': 'AAVE-USD',
        'WBTC': 'BTC-USD',
        'USDC': 'USDC-USD',
        'DAI': 'DAI-USD',
        'CRV': 'CRV-USD',
        'WETH': 'ETH-USD',
        'SNX': 'SNX-USD',
        'LINK': 'LINK-USD',
        'UNI': 'UNI-USD',
        'RENBTC': 'RENBTC-USD',
        'BADGER': 'BADGER-USD',
        'RARI': 'RARI-USD',
        'FRAX': 'FRAX-USD',
        'CEL': 'CEL-USD',
        'REN': 'REN-USD',
        'BZRX': 'BZRX-USD',
        'USDT': 'USDT-USD',
        'PICKLE': 'PICKLE-USD',
        'SPELL': 'SPELL-USD',
        'GHST': 'GHST-USD',
        'CURVE': 'CRV-USD',
        # Add or modify more assets and trading pairs for Coinbase
    },
    
    'Bittrex': {
        'MATIC': 'MATIC-USDT',
        'QUICK': 'QUICK-USDT',
        'SUSHI': 'SUSHI-USDT',
        'WMATIC': 'WMATIC-USDT',
        'AAVE': 'AAVE-USDT',
        'ETH': 'ETH-USDT',
        'DAI': 'DAI-USDT',
        'CRV': 'CRV-USDT',
        'SNX': 'SNX-USDT',
        'LINK': 'LINK-USDT',
        'UNI': 'UNI-USDT',
        'RENBTC': 'RENBTC-USDT',
        'BADGER': 'BADGER-USDT',
        'RARI': 'RARI-USDT',
        'FRAX': 'FRAX-USDT',
        'CEL': 'CEL-USDT',
        'REN': 'REN-USDT',
        'BZRX': 'BZRX-USDT',
        'USDT': 'USDT-USDT',
        'PICKLE': 'PICKLE-USDT',
        'SPELL': 'SPELL-USDT',
        'GHST': 'GHST-USDT',
        'CURVE': 'CRV-USDT',
        # Add or modify more assets and trading pairs for Bittrex
    },
    
    'Huobi': {
        'MATIC': 'maticusdt',
        'QUICK': 'quickusdt',
        'SUSHI': 'sushiusdt',
        'WMATIC': 'wmaticusdt',
        'AAVE': 'aaveusdt',
        'WBTC': 'btcusdt',
        'ETH': 'ethusdt',
        'DAI': 'daiusdt',
        'CRV': 'crvusdt',
        'WETH': 'ethusdt',
        'SNX': 'snxusdt',
        'LINK': 'linkusdt',
        'UNI': 'uniusdt',
        'RENBTC': 'renbtcusdt',
        'BADGER': 'badgerusdt',
        'RARI': 'rariusdt',
        'FRAX': 'fraxusdt',
        'CEL': 'celusdt',
        'REN': 'renusdt',
        'BZRX': 'bzrxusdt',
        'USDT': 'usdtusdt',
        'PICKLE': 'pickleusdt',
        'SPELL': 'spellusdt',
        'GHST': 'ghstusdt',
        'CURVE': 'crvusdt',
        # Add or modify more assets and trading pairs for Huobi
    },
    'OKEx': {
        'MATIC': 'MATIC-USDT',
        'MATIc': 'MATIC-USDC',
        'QUICK': 'QUICK-USDT',
        'SUSHI': 'SUSHI-USDT',
        'WMATIC': 'WMATIC-USDT',
        'AAVE': 'AAVE-USDT',
        'WBTC': 'WBTC-USDT',
        'ETH': 'ETH-USDT',
        'DAI': 'DAI-USDT',
        'CRV': 'CRV-USDT',
        'WETH': 'WETH-USDT',
        'SNX': 'SNX-USDT',
        'LINK': 'LINK-USDT',
        'UNI': 'UNI-USDT',
        'RENBTC': 'RENBTC-USDT',
        'BADGER': 'BADGER-USDT',
        'RARI': 'RARI-USDT',
        'FRAX': 'FRAX-USDT',
        'CEL': 'CEL-USDT',
        'REN': 'REN-USDT',
        'BZRX': 'BZRX-USDT',
        'USDT': 'USDT-USDT',
        'PICKLE': 'PICKLE-USDT',
        'SPELL': 'SPELL-USDT',
        'GHST': 'GHST-USDT',
        'CURVE': 'CURVE-USDT',
        # Add or modify more assets and trading pairs for OKEx
    },
    'Bitstamp': {
        'MATIC': 'MATICUSD',
        'QUICK': 'QUICKUSD',
        'SUSHI': 'SUSHIUSD',
        'WMATIC': 'WMATICUSD',
        'AAVE': 'AAVEUSD',
        'WBTC': 'XBTUSD',
        'ETH': 'ETHUSD',
        'DAI': 'DAIUSD',
        'CRV': 'CRVUSD',
        'WETH': 'ETHUSD',
        'SNX': 'SNXUSD',
        'LINK': 'LINKUSD',
        'UNI': 'UNIUSD',
        'RENBTC': 'RENBTCUSD',
        'BADGER': 'BADGERUSD',
        'RARI': 'RARIUSD',
        'FRAX': 'FRAXUSD',
        'CEL': 'CELUSD',
        'REN': 'RENUSD',
        'BZRX': 'BZRXUSD',
        'USDT': 'USDTUSD',
        'PICKLE': 'PICKLEUSD',
        'SPELL': 'SPELLUSD',
        'GHST': 'GHSTUSD',
        'CURVE': 'CRVUSD',
        # Add or modify more assets and trading pairs for Bitstamp
    },
}#REMEBER EXCHANGE LIKE OKEKX HAVE MATIC AND MATIc FOR USDT AND USDC MARK RESPECTIVELY
